### ISSUE TITLE
Bootnodes from 127.0.0.1 throw errors. 

### ISSUE THREAD

**Issue by 5chdn** [ethereum/pyethapp#125]
## Checklist
- [ ] installed `pyethapp` inside a virtualenv, nope
## System/environment
- OS: ArchLinux, kernel 4.5.1
- python version: 2.7.11
- pyethapp version: 1.2.1
- installation method (pip & pypi/git & setup.py): git & setup.py
- pyethapp branch (if applicable): develop
## Expected behaviour

Connect to peers, also accept bootnodes from localhost without any issues.
## Observed behaviour

Peers from 127.0.0.1 throw errors. 

```
INFO:p2p.peer received hello client_version=Geth/v1.4.0-unstable-798e4fb4/darwin/go1.6 version=4 capabilities=(('eth', 63), ('eth', 62), ('eth', 61))
INFO:p2p.peer received hello client_version=Geth/v1.1.3/linux/go1.5 version=4 capabilities=(('eth', 61), ('eth', 60))
INFO:p2p.peer received hello client_version=Gsoil/v1.4.0-9174da70/linux/go1.6.2 version=4 capabilities=(('eth', 63), ('eth', 62), ('eth', 61))
INFO:p2p.peer received hello client_version=Ethereum(J)/v1.2.0/Linux/Dev/Java/Dev version=4 capabilities=(('eth', 62),)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gevent-1.1.0-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/devp2p-0.7.2-py2.7.egg/devp2p/peer.py", line 266, in _run_ingress_message
    self.mux.add_message(imsg)
  File "/usr/lib/python2.7/site-packages/devp2p-0.7.2-py2.7.egg/devp2p/muxsession.py", line 51, in _add_message_during_handshake
    rest = session.decode_authentication(msg)
  File "/usr/lib/python2.7/site-packages/devp2p-0.7.2-py2.7.egg/devp2p/rlpxcipher.py", line 224, in decode_authentication
    (size, sig, initiator_pubkey, nonce, version) = self.decode_auth_eip8(ciphertext)
  File "/usr/lib/python2.7/site-packages/devp2p-0.7.2-py2.7.egg/devp2p/rlpxcipher.py", line 261, in decode_auth_eip8
    assert len(ciphertext) >= size
AssertionError
<Peer('127.0.0.1', 38790) > failed with AssertionError
```
## Steps to reproduce

Try to connect to a eth/geth/parity node on 127.0.0.1

```
pyethapp -l "eth:debug" -b "enode://6fb7872da1f2fd3820f8888315f806ffb1ef72449f772c50543a1c3aac4ae530ef467f42b280c9c11127b065fa4b6cd8c756a1bcd81a3dd9d5b59fe5ba24c362@127.0.0.1:30304" run
```

**Comment by ulope** [comment]
Fixed in #122
