### ISSUE TITLE
pyethapp fails on testnet transaction, fails to handle exception properly

### ISSUE THREAD

**Issue by iivvoo** [ethereum/pyethapp#140]
pyethapp (both from pypi (1.2.3) and built from master crash after appr. 600MB of testnet blockchain data (leveldb size monitored), after block <Block(#173522 6e252728)>
## Checklist
- [x] installed `pyethapp` inside a virtualenv
## System/environment
- OS: Ubuntu 14.04
- python version: 2.7.6
- pyethapp version: 1.2.3 + master
- installation method (pip & pypi/git & setup.py): pip install pyethapp (but also from master)
- pyethapp branch (if applicable): --
## Expected behaviour

I expected pyethapp to eventually download the entire testnet blockchain after invoking

```
bin/pyethapp --profile morden --data-dir ../state run
```

I've tried this with both the current master branch (git clone, setup -e editable . etc) and a pip installed version
## Observed behaviour

pyethapp crashes after about 600MB of blockchain data by not properly handling an invalid transaction

```

INFO:eth.chainservice   added txs=11 gas_used=1456400 block=<Block(#173519 5667dea2)>
INFO:eth.chainservice   added txs=11 gas_used=809768 block=<Block(#173520 a1ec179e)>
INFO:eth.chainservice   added txs=66 gas_used=2611847 block=<Block(#173521 539c1e93)>
INFO:eth.chainservice   added txs=12 gas_used=674968 block=<Block(#173522 6e252728)>
Traceback (most recent call last):
  File "/home/ivo/m3r/projects/Guts/ethereum/pyethapp-pip/local/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/ivo/m3r/projects/Guts/ethereum/pyethapp-pip/local/lib/python2.7/site-packages/pyethapp/eth_service.py", line 277, in _add_blocks
    except processblock.InvalidTransaction as e:
AttributeError: 'module' object has no attribute 'InvalidTransaction'
<Greenlet at 0x7f3f04f26870: <bound method ChainService._add_blocks of <ChainService at 0x7f3f0f4047d0>>> failed with AttributeError

INFO:p2p.peer   received hello client_version=Geth/Node1/v1.3.5/linux/go1.5.1 version=4 capabilities=(('eth', 63), ('eth', 62), ('eth', 61))
WARNING:eth.chainservice    invalid network id remote_network_id=1529417 expected_network_id=2
WARNING:protocol    protocol exception, stopping error=wrong network_id
INFO:p2p.peer   received hello client_version=Geth/v1.4.3-stable/linux/go1.5.1 version=4 capabilities=(('eth', 63), ('eth', 62), ('eth', 61))
WARNING:eth.chainservice    invalid network id remote_network_id=1 expected_network_id=2
WARNING:protocol    protocol exception, stopping error=wrong network_id
INFO:p2p.peer   received hello client_version=Geth/v1.4.5-stable-a269a713/linux/go1.6.2 version=4 capabilities=(('eth', 63), ('eth', 62), ('eth', 61))
INFO:p2p.peer   received hello client_version=Geth/v1.3.6/linux/go1.6.2 version=4 capabilities=(('eth', 63), ('eth', 62), ('eth', 61))
WARNING:eth.chainservice    invalid network id remote_network_id=909 expected_network_id=2
WARNING:protocol    protocol exception, stopping error=wrong network_id
INFO:p2p.peer   received hello client_version=Geth/v1.5.0-unstable/windows/go1.6.2 version=4 capabilities=(('eth', 63),)
```
## Steps to reproduce
- create virtualenv
- pip install pyethapp
- bin/pyethapp --profile morden --data-dir ../state run

wait...

Entire pip freeze:

```

backports.shutil-get-terminal-size==1.0.0
bitcoin==1.1.42
cffi==1.6.0
click==6.6
CodernityDB==0.5.0
coverage==4.1
decorator==4.0.10
devp2p==0.7.3
docutils==0.12
ethereum==1.3.5
gevent==1.1.0
gipc==0.4.0
greenlet==0.4.9
ipaddress==1.0.16
ipython==4.2.0
ipython-genutils==0.1.0
leveldb==0.193
lmdb==0.89
pathlib2==2.1.0
pbkdf2==1.3
pexpect==4.1.0
pickleshare==0.7.2
pluggy==0.3.1
ptyprocess==0.5.1
py==1.4.31
pycparser==2.14
pycryptodome==3.4
pyelliptic==1.5.7
pyethapp==1.2.3
pyethash==0.1.27
pysha3==0.3
PyYAML==3.11
repoze.lru==0.6
requests==2.10.0
rlp==0.4.5
scrypt==0.7.1
secp256k1==0.12.1
simplegeneric==0.8.1
six==1.10.0
statistics==1.0.3.5
tinyrpc==0.5
tox==2.3.1
traitlets==4.2.1
virtualenv==15.0.2
Werkzeug==0.11.10
```

**Comment by RomanZacharia** [comment]
https://github.com/ethereum/pyethereum/issues/327
