### ISSUE TITLE
pyethapp PoW service fails as soon as console is entered

### ISSUE THREAD

**Issue by pdaian** [ethereum/pyethapp#156]
Am running pyethapp 1.4.0 on Ubuntu 14.04 and OS X 10.11.x El Capitan, with identical behavior on both, both Python 2.7.x.

Steps to reproduce:
- Start pyethapp on private testnet, with mining enabled
- Use Ctrl-C to enter interactive console
- Use eth.chain.headnumber to watch mining progress

The following stacktrace also seems related, and occurs whenever the Ctrl-C is pressed to enter the interactive console:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyethapp-1.4.0-py2.7.egg/pyethapp/pow_service.py", line 169, in _run
    cmd, kargs = self.ppipe.get()
  File "/usr/local/lib/python2.7/dist-packages/gipc/gipc.py", line 679, in get
    msize, = struct.unpack("!i", self._recv_in_buffer(4).getvalue())
  File "/usr/local/lib/python2.7/dist-packages/gipc/gipc.py", line 634, in _recv_in_buffer
    "Most likely, the other pipe end is closed.")
EOFError: Most likely, the other pipe end is closed.
<PoWService at 0x7f9b1cd48a50> failed with EOFError
```

Because mining is not working, I also cannot submit transactions using the interactive console on a private testnet (as these transactions will just hang in memory until the process is killed with no other nodes/miners connected).

**Comment by gsalgado** [comment]
I wonder if this is the same issue that is causing test_logfilters_topics to fail for me: http://sprunge.us/IdOa

I'll keep digging to see if I find out what's the cause and maybe fix it
