### ISSUE TITLE
TypeError in usage of pyethash library

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/pyethapp#16]
```
Traceback (most recent call last):
  File "/Users/jillkatzenberger/python-environments/ethereum/lib/python2.7/site-packages/gevent-1.0.2-py2.7-macosx-10.10-x86_64.egg/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/jillkatzenberger/python-environments/ethereum/lib/python2.7/site-packages/devp2p-0.4.1-py2.7.egg/devp2p/peer.py", line 193, in _run_decoded_packets
    self._handle_packet(self.mux.packet_queue.get())  # get_packet blocks
  File "/Users/jillkatzenberger/python-environments/ethereum/lib/python2.7/site-packages/devp2p-0.4.1-py2.7.egg/devp2p/peer.py", line 167, in _handle_packet
    protocol.receive_packet(packet)
  File "/Users/jillkatzenberger/python-environments/ethereum/lib/python2.7/site-packages/devp2p-0.4.1-py2.7.egg/devp2p/protocol.py", line 164, in receive_packet
    cmd(packet)
  File "/Users/jillkatzenberger/python-environments/ethereum/lib/python2.7/site-packages/devp2p-0.4.1-py2.7.egg/devp2p/protocol.py", line 136, in receive
    instance.receive(proto=self, data=klass.decode_payload(packet.payload))
  File "/Users/jillkatzenberger/python-environments/ethereum/lib/python2.7/site-packages/devp2p-0.4.1-py2.7.egg/devp2p/protocol.py", line 72, in receive
    cb(proto, **data)
  File "/Users/jillkatzenberger/python-environments/ethereum/lib/python2.7/site-packages/pyethapp-0.9.18-py2.7.egg/pyethapp/eth_service.py", line 415, in on_receive_newblock
    self.synchronizer.receive_newblock(proto, block, chain_difficulty)
  File "/Users/jillkatzenberger/python-environments/ethereum/lib/python2.7/site-packages/pyethapp-0.9.18-py2.7.egg/pyethapp/synchronizer.py", line 293, in receive_newblock
    if not t_block.header.check_pow():
  File "/Users/jillkatzenberger/sites/pyethereum/ethereum/blocks.py", line 297, in check_pow
    self.difficulty)
  File "/Users/jillkatzenberger/python-environments/ethereum/lib/python2.7/site-packages/repoze.lru-0.6-py2.7.egg/repoze/lru/__init__.py", line 287, in lru_cached
    val = f(*arg)
  File "/Users/jillkatzenberger/sites/pyethereum/ethereum/ethpow.py", line 66, in check_pow
    cache = get_cache(block_number)
  File "/Users/jillkatzenberger/sites/pyethereum/ethereum/ethpow.py", line 45, in get_cache
    c = mkcache(block_number)
TypeError: function takes exactly 2 arguments (1 given)
<Greenlet at 0x108c527d0: <bound method Peer._run_decoded_packets of <Peer('54.207.93.166', 30303) Geth/v0.9.23>>> failed with TypeError
```

Looks like the call signature for mkcache may have changed.  I had trouble introspecting pyethash but it all appears to be c libraries.

**Comment by AFDudley** [comment]
This is the issue for the error:
https://github.com/ethereum/pyethereum/issues/259#issuecomment-105201532

**Comment by pipermerriam** [comment]
Thanks, sorry for tossing this in the wrong repo.

**Comment by heikoheiko** [comment]
fixed with new pypi package https://pypi.python.org/pypi/pyethash

**Comment by heikoheiko** [comment]
fixed with new pypi package https://pypi.python.org/pypi/pyethash
