### ISSUE TITLE
'secp256k1==0.12.1' distribution was not found

### ISSUE THREAD

**Issue by cheershendtco** [ethereum/pyethapp#171]
## Checklist
- [yes,but not sure] installed `pyethapp` inside a virtualenv
## System/environment
- OS: ubuntu 14
- python version:  2.7.6
- pyethapp version: pyethapp 1.5.0/linux2/py2.7.6
- installation method (pip & pypi/git & setup.py): git
- pyethapp branch (if applicable): FIXME
## Expected behaviour

FIXME
## Observed behaviour

pkg_resources.DistributionNotFound: The 'secp256k1==0.12.1' distribution was not found and is required by devp2p
## Steps to reproduce

i follow
https://github.com/ethereum/pyethapp/wiki/Getting-Started
after i type `pyethapp`
it shows 

```
pkg_resources.DistributionNotFound: The 'secp256k1==0.12.1' distribution was not found and is required by devp2p
```

more information below thanks.

```
(.venv) osboxes@osboxes:~/ethereum/pyethapp$ pyethapp
Traceback (most recent call last):
  File "/home/osboxes/ethereum/pyethapp/.venv/bin/pyethapp", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/osboxes/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/home/osboxes/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/home/osboxes/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/osboxes/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/osboxes/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/osboxes/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'secp256k1==0.12.1' distribution was not found and is required by devp2p
```

**Comment by ulope** [comment]
It looks like some of the dependencies are not installed correctly. Could you post the output of `pip list` from within the virtualenv?

**Comment by deerdear** [comment]
Hi! Having the same problem but on OSX. 
I get the following output from `pip list`:
bitcoin (1.1.42)
cffi (1.8.2)
CodernityDB (0.5.0)
gevent (1.1.0)
greenlet (0.4.10)
leveldb (0.193)
pbkdf2 (1.3)
pexpect (4.2.1)
pip (8.1.2)
ptyprocess (0.5.1)
pycparser (2.14)
pycryptodome (3.4)
pysha3 (0.3)
PyYAML (3.12)
repoze.lru (0.6)
scrypt (0.7.1)
setuptools (27.2.0)
wheel (0.30.0a0)

What's missing?

*Edit: Actually not exactly the same issue. Creating new...

**Comment by irghis** [comment]
I had the same problem and when you solve it more problems are generated. I will put the commands I used in order to solve the chain of problems.
1. Install/update  "devp2p". 
   `pip install devp2p --upgrade`
2. (optional) It is possible that you upgraded "gevent" version (I did), don't. It doesn't work with gevent 1.1.2, but just with 1.1.0
   `pip uninstall gevent
   pip install gevent==1.1.0`
3. Fix greenlet dependencies.
   `pip uninstall greenlet
   easy_install greenlet`

After that you should be able to execute pyethapp by typing `pyethapp` from your virtual environment in the terminal.

**Comment by ulope** [comment]
@deerdear:
You're missing quite a lot of dependencies. 

Here is the list of installed packages in a fresh virtualenv after running `pip install pyethapp`:

```
backports.shutil-get-terminal-size (1.0.0)
bitcoin (1.1.42)
cffi (1.8.3)
click (6.6)
CodernityDB (0.5.0)
coverage (4.2)
decorator (4.0.10)
devp2p (0.8.0)
docutils (0.12)
enum34 (1.1.6)
ethereum (1.5.2)
gevent (1.1.0)
gipc (0.4.0)
greenlet (0.4.10)
ipaddress (1.0.17)
ipython (4.2.1)
ipython-genutils (0.1.0)
leveldb (0.194)
lmdb (0.89)
pathlib2 (2.1.0)
pbkdf2 (1.3)
pexpect (4.2.1)
pickleshare (0.7.4)
pip (8.1.2)
pluggy (0.3.1)
ptyprocess (0.5.1)
py (1.4.31)
pycparser (2.14)
pycryptodome (3.4)
pyelliptic (1.5.7)
pyethapp (1.5.0)
pyethash (0.1.27)
pysha3 (0.3)
PyYAML (3.12)
repoze.lru (0.6)
requests (2.11.1)
rlp (0.4.6)
scrypt (0.8.0)
secp256k1 (0.12.1)
setuptools (27.2.0)
simplegeneric (0.8.1)
six (1.10.0)
statistics (1.0.3.5)
tinyrpc (0.5)
tox (2.3.1)
traitlets (4.3.0)
virtualenv (15.0.3)
Werkzeug (0.11.11)
wheel (0.30.0a0)
```

You could try `pip install --upgrade --force-reinstall pyethapp` and see if that fixes the problem.

However I wonder how you got into that situation in the first place. Installing pyethapp installs all required dependencies automatically.

**Comment by cheershendtco** [comment]
`pip install --upgrade --force-reinstall pyethapp`
works for me thanks a lot

after I `pyethapp run`
it starts running.

Q1:
should I `~/ethereum/pyethapp$ source .venv/bin/activate`
every time when I want to `pyethapp run`

is it a must ? `Starting pyethapp from outside of the virtual environment`
if no I would like to `~/ethereum/pyethapp$ source .venv/bin/activate` every time.
thanks

Q2: 
I got a UserWarning. should I have to solve it?
(.venv) osboxes@osboxes:~/ethereum/pyethapp$ pyethapp
/home/osboxes/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/Crypto/Hash/keccak.py:139: `UserWarning`: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  c_size_t(self.digest_size))
Usage: pyethapp [OPTIONS] COMMAND [ARGS]...

  Welcome to pyethapp undefined/linux2/py2.7.12

Q3:
not start syncing the blockchain
I use 
`sudo pyethapp run --console`
and

```

In [1]: eth.latest
Out[1]: CachedBlock(#0 d4e56740)

In [2]: eth.latest
Out[2]: CachedBlock(#0 d4e56740)

```

it looks not start syncing the blockchain?

more information

```
In [12]: eth.services.peermanager.peers
Out[12]: 
[<Peer('144.76.62.101', 30303) pyethapp/v1.4.0>,
 <Peer('169.45.222.221', 30303) Geth/v1.5.0-unstable>,
 <Peer('198.199.82.46', 30303) Ethereum(J)/v1.3.0>,
 <Peer('159.203.191.125', 30303) Ethereum(J)/v1.3.0>]

```

Q4:
if I want To access the testnet 
and I follow https://github.com/ethereum/pyethapp/wiki/Running-the-Testnet
I use
`sudo pyethapp --profile morden --data-dir '/home/user/Ethereum/pyethapp/state' run --console`
is that correct?

more information

```

In [40]: eth.services.peermanager.peers
Out[40]: []

In [41]: eth.latest
Out[41]: <CachedBlock(#0 0cd786a2)>

```

almost 2 hours. looks like my testnet does not  sync.

Thanks in advance.

**Comment by cheershendtco** [comment]
hihi
about Q3:
after I wait for a while
it start syncing

```

In [5]: eth.latest
Out[5]: <CachedBlock(#4492 0cfea1b2)>

In [6]: eth.latest
Out[6]: <CachedBlock(#4568 b88dce26)>

```
