### ISSUE TITLE
Valid genesis file rejected due to capitalization difference

### ISSUE THREAD

**Issue by Smithgift** [ethereum/pyethapp#174]
In the process of building a pyethapp Dockerfile for [hive](https://github.com/karalabe/hive), I discovered that pyethapp will reject a perfectly valid genesis json if the capitalization of the keys is different than expected. (Specifically: `mixHash` vs. `mixhash`)
## Checklist
- [ ] installed `pyethapp` inside a virtualenv (used Docker instead)
## System/environment
- OS: Ubuntu 16.04
- python version: 2.7.12
- pyethapp version: 1.5.0/linux2/py2.7.12
- installation method (pip & pypi/git & setup.py): git and setup.py
- pyethapp branch (if applicable): develop
## Expected behaviour

A successful import of a standard genesis.json file. I used [this .json](https://github.com/karalabe/hive/blob/master/validators/smoke/genesis-chain/genesis.json) from hive.
## Observed behaviour

It fails like the following

```
/usr/local/lib/python2.7/dist-packages/pycryptodome-3.4-py2.7-linux-x86_64.egg/Crypto/Hash/keccak.py:139: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  c_size_t(self.digest_size))

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

INFO:config setup default config path=/root/.config/pyethapp
INFO:config writing config path=/root/.config/pyethapp/config.yaml
INFO:app    using data in path=/root/.config/pyethapp
INFO:config loading config path=/root/.config/pyethapp
Traceback (most recent call last):
  File "/usr/local/bin/pyethapp", line 11, in <module>
    load_entry_point('pyethapp', 'console_scripts', 'pyethapp')()
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 1057, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/pyethapp/pyethapp/app.py", line 148, in app
    genesis_json_filename_or_dict=config['eth']['genesis'])
  File "/pyethapp/pyethapp/config.py", line 207, in update_config_from_genesis_json
    raise ValueError('genesis_dict contains invalid keys.')
ValueError: genesis_dict contains invalid keys.
```
## Steps to reproduce

Use that .json up there, or just change the capitalization of `mixHash` in a working .json.

FYI, [these](https://github.com/ethereum/pyethapp/blob/develop/pyethapp/config.py#L200-L207) are the offending lines. I'd fix it myself, but I'm not sure what you'd want done. Is it supposed to be case-insensitive? Is pyethapp right in this instance, and it's the other implementations that are wrong?

**Comment by Smithgift** [comment]
In addition, a genesis.json will be rejected if contains an `0x` in an address in the allocation. [This](https://raw.githubusercontent.com/karalabe/hive/master/validators/smoke/testnet-nonces/genesis.json) file has both issues, for easy testing.
