### ISSUE TITLE
More secp256k1 issues.

### ISSUE THREAD

**Issue by roguethunderbird** [ethereum/pyethapp#178]
## Checklist
- [x] installed `pyethapp` inside a virtualenv

## System/environment

- OS: Lubuntu 16.10 (Also Xubuntu 16.04.1)
- python version: 2.7.12+
- pyethapp version: 1.5.0
- installation method (pip & pypi/git & setup.py): pip & git & setup.py
- pyethapp branch (if applicable): N/A

## Expected behaviour
For pyethapp to... run.

## Observed behaviour
(.venv) gijon@gijon:~/ethereum/pyethapp$ pyethapp
Traceback (most recent call last):
  File "/home/gijon/ethereum/pyethapp/.venv/bin/pyethapp", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/gijon/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/home/gijon/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/home/gijon/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/gijon/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/gijon/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/gijon/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'secp256k1==0.12.1' distribution was not found and is required by devp2p

## Steps to reproduce
Followed https://github.com/ethereum/pyethapp/wiki/Getting-Started
With the additon of having to preinstall:
build-essential
libssl-dev
python-pip (not preinstalled with preinstalled py2.7.12)
pkg-config
git

## Additional Information
Probably related to https://github.com/ethereum/pyethapp/issues/171

I believe related to issues with secp256k1 getting updated to 0.13.2 in the wild. In a previous attempt I tried to manually install version 0.12.1 via pip install secp256k1==0.12.1 but encountered errors in doing so.
Started over with full sanitized VM.

My pip list...
```
(.venv) gijon@gijon:~/ethereum/pyethapp$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
backports.shutil-get-terminal-size (1.0.0)
bitcoin (1.1.42)
cffi (1.8.3)
click (6.6)
CodernityDB (0.5.0)
coverage (4.2)
decorator (4.0.10)
devp2p (0.8.0)
docutils (0.12)
enum34 (1.1.6)
ethereum (1.6.0)
gevent (1.1.0)
gipc (0.4.0)
greenlet (0.4.10)
ipaddress (1.0.17)
ipython (4.2.1)
ipython-genutils (0.1.0)
leveldb (0.194)
lmdb (0.92)
pathlib2 (2.1.0)
pbkdf2 (1.3)
pexpect (4.2.1)
pickleshare (0.7.4)
pip (9.0.1)
pkg-resources (0.0.0)
pluggy (0.4.0)
ptyprocess (0.5.1)
py (1.4.31)
pycparser (2.17)
pycryptodome (3.4.3)
pyelliptic (1.5.7)
pyethapp (1.5.0, /home/gijon/ethereum/pyethapp)
pyethash (0.1.27)
pysha3 (0.3)
PyYAML (3.12)
repoze.lru (0.6)
requests (2.11.1)
rlp (0.4.6)
scrypt (0.8.0)
secp256k1 (0.13.2)
setuptools (28.8.0)
simplegeneric (0.8.1)
six (1.10.0)
statistics (1.0.3.5)
tinyrpc (0.5)
tox (2.4.1)
traitlets (4.3.1)
virtualenv (15.0.3)
Werkzeug (0.11.11)
wheel (0.30.0a0)
(.venv) gijon@gijon:~/ethereum/pyethapp$

```

**Comment by alex-miller-0** [comment]
Same problem here on OSX Sierra 10.12.3. 

I believe the issue is with the dependency coming from devp2p: `pkg_resources.ContextualVersionConflict: (secp256k1 0.13.2 (/Users/alexmiller/eth/python/pyethapp/.venv/lib/python2.7/site-packages), Requirement.parse('secp256k1==0.12.1'), set(['devp2p']))`

Not possible to manually install `0.12.1` via pip for me either.

**Comment by alex-miller-0** [comment]
There is an open PR for devp2p that would resolve this: https://github.com/ethereum/pydevp2p/pull/53
