### ISSUE TITLE
RPC cannot handle id of bare zero.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/pyethapp#181]
In the midst of creating a pyethapp (develop branch) harness for hive, I discovered that giving a RPC call an id of `0` will cause it to never reply, since on the server's side it throws an exception. Here's a simple command to test that:

```
curl -s -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x0", false],"id":0}' localhost:8545
```

If the zero is a string `"0"` it will handle it just fine. Otherwise, it'll just never reply.

Here's a backtrace, server-side:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1.0-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "build/bdist.linux-x86_64/egg/tinyrpc/server/__init__.py", line 51, in handle_message
    response = self.dispatcher.dispatch(request)
  File "/pyethapp/pyethapp/jsonrpc.py", line 121, in dispatch
    self.logger('RPC error', id=res.unique_id, error=res.error)
AttributeError: 'NoneType' object has no attribute 'unique_id'
<Greenlet at 0x7fe6a051ac30: handle_message(<Queue at 0x7fe6a053d310 getters[1]>, '{"jsonrpc":"2.0","method":"eth_getBlockByNumber",)> failed with AttributeError
``

**Comment by cdetrio** [comment]
This is due to an issue with tinyrpc https://github.com/mbr/tinyrpc/issues/27
