### ISSUE TITLE
syncing issues

### ISSUE THREAD

**Issue by anithag** [ethereum/pyethapp#183]
## Checklist
- [x] installed `pyethapp` inside a virtualenv

## System/environment

- OS: MAC OS X 10.12.1
- python version: 2.7.10
- pyethapp version: github clone
- installation method (pip & pypi/git & setup.py): git & setup.py
- pyethapp branch (if applicable): master

I am using pyethapp as follows:

`pyethapp --profile morden run --console`

This gives the following ( trailing )output and is stuck during syncing (I waited for 2 hrs and still no peers got connected. I am assuming this is an issue as there is no progress at all from block 0)
    
    INFO:app	registering service service=accounts
    INFO:db	No contrib directory found, so not loading any user services 
    INFO:db	opening LevelDB path=/Users/anithagollamudi/Library/Application  
    Support/pyethapp/leveldb max_open_files=128 block_cache_size=8388608 
    write_buffer_size=4194304
    INFO:app	registering service service=db
    INFO:p2p.discovery	NodeDiscovery init 
    INFO:p2p.discovery	starting discovery proto     this_enode=enode://9ef55ab3081b7e449590213477590e492d4e9a626aee79e3d17fdf2530af3a6a92a19f2789c4b398781957a5e44ea356996af2e3f60c2f8a4e050ff814c173b1@0.0.0.0:30303
    INFO:app	registering service service=discovery
    INFO:p2p.peermgr	PeerManager init 
    INFO:app	registering service service=peermanager
    INFO:eth.chainservice	initializing chain 
    INFO:eth.chainservice	chain at number=0
    INFO:app	registering service service=chain
    WARNING:jsonrpc	could not import solidity  
    INFO:app	registering service service=jsonrpc
    WARNING:jsonrpc	could not import solidity 
    INFO:app	registering service service=ipc
    INFO:app	registering service service=console
    INFO:app	starting 
    INFO:p2p.peermgr	starting peermanager 
    INFO:p2p.peermgr	starting listener addr=('0.0.0.0', 30303)
    INFO:p2p.discovery	starting discovery 
    INFO:p2p.discovery	starting listener host=0.0.0.0 port=30303 `
    In [16]: eth.services.peermanager.peers
    Out[16]: []

## Expected behaviour
Some connected peers

## Observed behaviour
No connected peers

## Steps to reproduce
Run the command on latest githhub version on MAC OS X.

If this is not the right way to run morden, let me know.

**Comment by LiyanJin** [comment]
try this
pyethapp --profile testnet run --console
I tried this and received hello from other clients. However, the client can't do syncing.
Any idea?

**Comment by janx** [comment]
Because pyethapp only support wire protocol p61 and geth has upgraded to p62/p63.

You can find a working in progress p62 implementation [here](https://github.com/ethereum/pyethapp/pull/176). It's not stable yet and I'm still investigating some disconnect issues, but you're welcome to try and report bugs :-)

**Comment by LiyanJin** [comment]
Thank u so much. I am bothered by this problem for a week. 
BTW, r u from China?

**Comment by LiyanJin** [comment]
I have downloaded and installed the pyethapp, pyethereum and pydevp2p which are on your branch. The new pyethapp does connect with Geth well in my private chain. However, pyethapp gives the following output when it  was trying to sync with Geth.  Any idea?

INFO:eth.sync.task	spawning new synctask 
INFO:eth.sync.task	downloaded 32 blockheaders start=#66 69cde4f9 end=#35 87a64557
INFO:eth.sync.task	downloaded 66 blockheaders start=#66 69cde4f9 end=#1 23627a5a
Traceback (most recent call last):
  File "/home/pi/myproject/ethereum/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/pi/myproject/ethereum/pyethapp/pyethapp/eth_service.py", line 300, in _add_blocks
    if self.chain.add_block(block, forward_pending_transactions=self.is_mining):
  File "/home/pi/myproject/ethereum/lib/python2.7/site-packages/ethereum-1.6.0-py2.7.egg/ethereum/chain.py", line 303, in add_block
    processblock.verify(block, block.get_parent())
  File "/home/pi/myproject/ethereum/lib/python2.7/site-packages/ethereum-1.6.0-py2.7.egg/ethereum/processblock.py", line 38, in verify
    env=parent.env, parent=parent)
  File "/home/pi/myproject/ethereum/lib/python2.7/site-packages/rlp/codec.py", line 214, in decode
    obj = sedes.deserialize(item, **kwargs)
  File "/home/pi/myproject/ethereum/lib/python2.7/site-packages/rlp/sedes/lists.py", line 248, in deserialize
    obj = cls(**dict(list(params.items()) + list(kwargs.items())))
  File "/home/pi/myproject/ethereum/lib/python2.7/site-packages/ethereum-1.6.0-py2.7.egg/ethereum/blocks.py", line 460, in __init__
    raise ValueError("Block's difficulty is inconsistent with its parent's difficulty")
ValueError: Block's difficulty is inconsistent with its parent's difficulty
<Greenlet at 0x746c8a80: <bound method ChainService._add_blocks of <ChainService at 0x750d7df0
>>> failed with ValueError

The difficulty of my genesis block is set up as 0x200 for both Pyethapp and Geth.
Below are are some more information about my pyethapp.
eth:
  block:
    ACCOUNT_INITIAL_NONCE: 0
    ANTI_DOS_FORK_BLKNUM: 2457000
    BLKLIM_FACTOR_DEN: 2
    BLKLIM_FACTOR_NOM: 3
    BLOCK_DIFF_FACTOR: 2048
    BLOCK_REWARD: *id001
    CHILD_DAO_LIST: *id002
    CLEARING_FORK_BLKNUM: *id003
    DAO_FORK_BLKEXTRA: dao-hard-fork
    DAO_FORK_BLKNUM: 1920000
    DAO_WITHDRAWER: !!binary |
      v07Xsn8dZmVG4w101Q0XPSC8p1Q=
    DIFF_ADJUSTMENT_CUTOFF: 13
    EXPDIFF_FREE_PERIODS: 2
    EXPDIFF_PERIOD: 100000
    GASLIMIT_ADJMAX_FACTOR: 1024
    GASLIMIT_EMA_FACTOR: 1024
    GENESIS_COINBASE: !!binary |
      VaMIio7mCcatSCsLlw4b5gVnkFw=
    GENESIS_DIFFICULTY: 512
    GENESIS_EXTRA_DATA: "2\b2p"
    GENESIS_GAS_LIMIT: 134217728
    GENESIS_INITIAL_ALLOC:
      55a3088a8ee609c6ad482b0b970e1be60567905c: {balance: '0'}
    GENESIS_MIXHASH: "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
      \0\0"
    GENESIS_NONCE: !!binary |
      EjRWeJEBESE=
    GENESIS_PREVHASH: "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
      \0\0"
    GENESIS_TIMESTAMP: 0
    HOMESTEAD_DIFF_ADJUSTMENT_CUTOFF: 10
    HOMESTEAD_FORK_BLKNUM: 1150000
    MAX_EXTRADATA_LENGTH: 32
    MAX_GAS_LIMIT: *id004
    MAX_UNCLES: 2
    MAX_UNCLE_DEPTH: 6
    METROPOLIS_BLOCKHASH_STORE: 32
    METROPOLIS_DIFF_ADJUSTMENT_CUTOFF: 9
    METROPOLIS_ENTRY_POINT: *id005
    METROPOLIS_FORK_BLKNUM: *id006
    METROPOLIS_GETTER_CODE: !!binary |
      YAA1VGAgUmAgYCDz
    METROPOLIS_STATEROOT_STORE: 16
    METROPOLIS_WRAPAROUND: 65536
    MIN_DIFF: 131072
    MIN_GAS_LIMIT: 5000
    NEPHEW_REWARD: *id007
    POW_EPOCH_LENGTH: 30000
    UNCLE_DEPTH_PENALTY_FACTOR: 8
  genesis: /home/pi/myproject/ethereum/pyethapp/privatechain/genesis.json
  network_id: 1999
  pruning: -1
ipc: {ipcpath: /tmp/pyethapp.ipc}
jsonrpc: {corsdomain: '', listen_host: 127.0.0.1, listen_port: 4000}
log_disconnects: false
node: {privkey_hex: 72************************************************************98}
p2p:
  bootstrap_nodes: []
  listen_host: 0.0.0.0
  listen_port: 30303
  max_peers: 10
  min_peers: 1
post_app_start_callback: null
pow: {activated: false, coinbase_hex: null, cpu_pct: 100, mine_empty_blocks: true}

WARNING:accounts	keystore directory does not exist directory=/home/pi/myproject/ethereum/pyethapp/privatechain/keystore
WARNING:accounts	no accounts found 
INFO:app	registering service service=accounts
INFO:db	No contrib directory found, so not loading any user services 
INFO:db	opening LevelDB path=/home/pi/myproject/ethereum/pyethapp/privatechain/leveldb max_open_files=128 block_cache_size=8388608 write_buffer_size=4194304
INFO:app	registering service service=db
INFO:p2p.discovery	NodeDiscovery init 
INFO:p2p.discovery	starting discovery proto this_enode=enode://42f381c7b59d38de954c53645419a8b5e0efa6787d5998df45b0b26e856d2ecd9003d71a2a57fa0c063ef254baf398b4b157590f4d29da5abaf6275bafcbf4e0@0.0.0.0:30303
INFO:app	registering service service=discovery
INFO:p2p.peermgr	PeerManager init 
INFO:app	registering service service=peermanager
INFO:eth.chainservice	initializing chain 
INFO:eth.chain	Initializing new chain 
INFO:eth.chain	new genesis difficulty=512 genesis_hash=<Block(#0 bef72bbe)>
INFO:eth.chainservice	chain at number=0
INFO:app	registering service service=chain
WARNING:jsonrpc	could not import solidity 
INFO:app	registering service service=jsonrpc
WARNING:jsonrpc	could not import solidity 
INFO:app	registering service service=ipc
INFO:app	registering service service=console
INFO:app	starting 
INFO:p2p.peermgr	starting peermanager 
INFO:p2p.peermgr	starting listener addr=('0.0.0.0', 30303)
INFO:p2p.discovery	starting discovery 
INFO:p2p.discovery	starting listener host=0.0.0.0 port=30303
INFO:jsonrpc	starting IPCRPCServer ipcpath=/tmp/pyethapp.ipc
INFO:jsonrpc	starting JSONRPCServer port=4000
INFO:p2p.peermgr	waiting for bootstrap 
/home/pi/myproject/ethereum/lib/python2.7/site-packages/Crypto/Cipher/_mode_ecb.py:122: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  c_size_t(len(plaintext)))

**Comment by janx** [comment]
You may need to adjust `MIN_DIFF` as well:

> MIN_DIFF: 131072

**Comment by LiyanJin** [comment]
Hi  @Janx,
Thx for your  suggestion!
One more question. How and where can I adjust MIN_DIFF ?

**Comment by janx** [comment]
I think it's hard coded, which can only be modified in source: https://github.com/ethereum/pyethereum/blob/develop/ethereum/config.py

**Comment by LiyanJin** [comment]
I have modified MIN_DIFF to 100 in the config.py of ethereum and reinstall the pyethereum.  However,  the same error come.
ValueError("Block's difficulty is inconsistent with its parent's difficulty")
Do you think I should modify the blocks.py as well

**Comment by LiyanJin** [comment]
@janx I run your pyethapp successfully with Geth in my private chain.
A little problem. When  the pyethapp is running,  the error warning appears as below. 
Traceback (most recent call last):
  File "/home/pi/myproject/ethereum/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/pi/myproject/ethereum/lib/python2.7/site-packages/devp2p-0.8.0-py2.7.egg/devp2p/peer.py", line 270, in _run_ingress_message
    self.mux.add_message(imsg)
  File "/home/pi/myproject/ethereum/lib/python2.7/site-packages/devp2p-0.8.0-py2.7.egg/devp2p/muxsession.py", line 51, in _add_message_during_handshake
    rest = session.decode_authentication(msg)
  File "/home/pi/myproject/ethereum/lib/python2.7/site-packages/devp2p-0.8.0-py2.7.egg/devp2p/rlpxcipher.py", line 224, in decode_authentication
    (size, sig, initiator_pubkey, nonce, version) = self.decode_auth_eip8(ciphertext)
  File "/home/pi/myproject/ethereum/lib/python2.7/site-packages/devp2p-0.8.0-py2.7.egg/devp2p/rlpxcipher.py", line 261, in decode_auth_eip8
    assert len(ciphertext) >= size
AssertionError
<Peer('151.80.42.204', 43007) > failed with AssertionError
Any idea?

BTW , how to start mining in pyethapp?

**Comment by LiyanJin** [comment]
I meet a strange problem today. When I run pyethapp in my private chain as normal, the error warning appears as below.

Traceback (most recent call last):
  File "/usr/local/bin/pyethapp", line 7, in <module>
    from pyethapp.app import app
  File "/usr/local/lib/python2.7/dist-packages/pyethapp/app.py", line 15, in <module>
    from devp2p.app import BaseApp
  File "/usr/local/lib/python2.7/dist-packages/devp2p/app.py", line 5, in <module>
    import crypto
  File "/usr/local/lib/python2.7/dist-packages/devp2p/crypto.py", line 7, in <module>
    import pyelliptic
  File "/usr/local/lib/python2.7/dist-packages/pyelliptic/__init__.py", line 43, in <module>
    from .openssl import OpenSSL
  File "/usr/local/lib/python2.7/dist-packages/pyelliptic/openssl.py", line 528, in <module>
    OpenSSL = _OpenSSL(libname)
  File "/usr/local/lib/python2.7/dist-packages/pyelliptic/openssl.py", line 180, in __init__
    self.ECDH_OpenSSL = self._lib.ECDH_OpenSSL
  File "/usr/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1: undefined symbol: ECDH_OpenSSL

Any idea?

**Comment by yuyuyuyuyuyuyuyuyu** [comment]
Question: AttributeError: /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1: undefined symbol: ECDH_OpenSSL

You can try ：sudo pip install pyelliptic==1.5.7.
