### ISSUE TITLE
python setup.py install does not install pyelliptic

### ISSUE THREAD

**Issue by AFDudley** [ethereum/pyethapp#2]
From a clean virtualenv:
$ python setup.py install
$ pyethapp
Traceback (most recent call last):
  File "/Users/rix/code/.virtualenvs/randnums/bin/pyethapp", line 9, in <module>
    load_entry_point('pyethapp==0.1.1', 'console_scripts', 'pyethapp')()
  File "/Users/rix/code/.virtualenvs/randnums/lib/python2.7/site-packages/pkg_resources/__init__.py", line 546, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/rix/code/.virtualenvs/randnums/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2666, in load_entry_point
    return ep.load()
  File "/Users/rix/code/.virtualenvs/randnums/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2339, in load
    return self.resolve()
  File "/Users/rix/code/.virtualenvs/randnums/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2345, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/rix/code/.virtualenvs/randnums/lib/python2.7/site-packages/pyethapp-0.1.1-py2.7.egg/pyethapp/app.py", line 11, in <module>
    from devp2p.peermanager import PeerManager
  File "/Users/rix/code/.virtualenvs/randnums/lib/python2.7/site-packages/devp2p-0.0.4-py2.7.egg/devp2p/peermanager.py", line 9, in <module>
    from peer import Peer
  File "/Users/rix/code/.virtualenvs/randnums/lib/python2.7/site-packages/devp2p-0.0.4-py2.7.egg/devp2p/peer.py", line 8, in <module>
    from muxsession import MultiplexedSession
  File "/Users/rix/code/.virtualenvs/randnums/lib/python2.7/site-packages/devp2p-0.0.4-py2.7.egg/devp2p/muxsession.py", line 3, in <module>
    from rlpxcipher import RLPxSession
  File "/Users/rix/code/.virtualenvs/randnums/lib/python2.7/site-packages/devp2p-0.0.4-py2.7.egg/devp2p/rlpxcipher.py", line 4, in <module>
    from devp2p.crypto import sha3
  File "/Users/rix/code/.virtualenvs/randnums/lib/python2.7/site-packages/devp2p-0.0.4-py2.7.egg/devp2p/crypto.py", line 30, in <module>
    if not CIPHERNAMES.issubset(set(pyelliptic.Cipher.get_all_cipher())):
NameError: name 'pyelliptic' is not defined

**Comment by AFDudley** [comment]
This may be related to the fact that pydevp2p assumes that OSX uses brew to install openssl. I used macports, which from what I can tell installs openssl correctly.

**Comment by heikoheiko** [comment]
confirmed. can you tell me the library path of openssl when installed with macports?

**Comment by AFDudley** [comment]
/opt/local/lib/libcrypto.dylib

pyelliptic found this with no issue.

**Comment by heikoheiko** [comment]
fixed in b7b2a9f2ea0d0243840f812214ec235adabcd3d6
