### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by marianmoldovan** [ethereum/pyethapp#20]
I am getting an error of missing module 'canary' after simple invoking 'pyethapp'. The error log is:

```
Traceback (most recent call last):
  File "/usr/local/bin/pyethapp", line 9, in <module>
    load_entry_point('pyethapp==0.9.18', 'console_scripts', 'pyethapp')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/pyethapp-0.9.18-py2.7.egg/pyethapp/app.py", line 14, in <module>
    from eth_service import ChainService
  File "/usr/local/lib/python2.7/dist-packages/pyethapp-0.9.18-py2.7.egg/pyethapp/eth_service.py", line 23, in <module>
    from pyethapp.canary import canary_addresses
ImportError: No module named canary
```

**Comment by heikoheiko** [comment]
fixed in be2890360316dd91c403f4857d05af30f8b4b805
