### ISSUE TITLE
'InputHookManager' object has no attribute 'register'

### ISSUE THREAD

**Issue by marianmoldovan** [ethereum/pyethapp#21]
I am getting this error after simple invoking 'pyethapp'. The error log is:

```
Traceback (most recent call last):
  File "/usr/local/bin/pyethapp", line 9, in <module>
    load_entry_point('pyethapp==0.9.18', 'console_scripts', 'pyethapp')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/pyethapp-0.9.18-py2.7.egg/pyethapp/app.py", line 15, in <module>
    from console_service import Console
  File "/usr/local/lib/python2.7/dist-packages/pyethapp-0.9.18-py2.7.egg/pyethapp/console_service.py", line 27, in <module>
    @inputhook_manager.register('gevent')
AttributeError: 'InputHookManager' object has no attribute 'register'
```

**Comment by atkummer** [comment]
How was this closed? I'm getting the same error.

Thanks.

**Comment by amiller** [comment]
I also get this error

**Comment by bundlking** [comment]
@marianmoldovan @atkummer @amiller - issue for me, on mac osx was an out of date iPython from an old anaconda install. Seem to be making progress having updated per instructions here - http://ipython.org/install.html
