### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ECC'

### ISSUE THREAD

**Issue by openpaul** [ethereum/pyethapp#210]
## Checklist
- [x] installed `pyethapp` inside a virtualenv

## System/environment

- OS: Debian testing
- python version: python2.7
- pyethapp version: pyethapp-1.5.0-py2.py3-none-any.whl 
- installation method (pip & pypi/git & setup.py): sudo pip install pyethapp
- pyethapp branch (if applicable): -

## Expected behaviour
pyethapp
## Observed behaviour
```bash
(pyethapp) user@pc:$ pyethapp
Traceback (most recent call last):
  File "/home/user/.virtualenvs/pyethapp/bin/pyethapp", line 7, in <module>
    from pyethapp.app import app
  File "/home/user/.virtualenvs/pyethapp/local/lib/python2.7/site-packages/pyethapp/app.py", line 15, in <module>
    from devp2p.app import BaseApp
  File "/home/user/.virtualenvs/pyethapp/local/lib/python2.7/site-packages/devp2p/app.py", line 8, in <module>
    from devp2p import crypto
  File "/home/user/.virtualenvs/pyethapp/local/lib/python2.7/site-packages/devp2p/crypto.py", line 42, in <module>
    class ECCx(pyelliptic.ECC):
AttributeError: 'module' object has no attribute 'ECC'
```

## Steps to reproduce
Install and start on debian 8

**Comment by BrianJKoopman** [comment]
pyelliptic has been deprecated by the author. For the final release they removed the ECDH/ECDSA support, which is what's causing the AttributeError here.

https://github.com/yann2192/pyelliptic/issues/50

**Comment by BrianJKoopman** [comment]
It looks like pyelliptic was deprecated by the author. In the final release they removed ECDH/ECDSA support, which is the root cause of the error here.

https://github.com/yann2192/pyelliptic/issues/50
