### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by greatken999** [ethereum/pyethapp#214]
`pip install pyethapp
Downloading gipc-0.4.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rh8m4fpb/gipc/setup.py", line 22, in <module>
        long_description=open("README.rst").read().decode('utf-8'),
    AttributeError: 'str' object has no attribute 'decode'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rh8m4fpb/gipc/
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

## Checklist
- [x] installed `pyethapp` inside a virtualenv

## System/environment

- OS: ubuntu 16.04
- python version: 3.5.2
- pyethapp version: 1.5.0
- installation method (pip & pypi/git & setup.py): pip
- pyethapp branch (if applicable): FIXME

## Expected behaviour
FIXME

## Observed behaviour
FIXME

## Steps to reproduce
pip install pyethapp

**Comment by greatken999** [comment]
this bug not found when use "pip2 install pyethapp"

**Comment by sstoner** [comment]
the same issue
system:  Sierra 10.12.5
env: python 3.6

**Comment by lordi** [comment]
This also happens with python 3.4. At least the installation can be fixed with using ``gipc==0.6.0`` in requirements.txt. Haven't made any further tests.

Edit: Ah, Python 3 is not supported.

**Comment by AndreMiras** [comment]
Wasn't the support for Python3 added in gipc==0.6.0?

**Comment by AndreMiras** [comment]
I believe this is now fixed with https://github.com/ethereum/pyethapp/pull/266

**Comment by mowshon** [comment]
pip**2** install pyethapp

**Comment by mowshon** [comment]
Just use:
```sudo pip install pyethapp==1.5.1a0```
