### ISSUE TITLE
AttributeError: /lib64/libcrypto.so.10: undefined symbol: EVP_CIPHER_CTX_reset

### ISSUE THREAD

**Issue by koreymacdougall** [ethereum/pyethapp#234]
## Checklist
- [x] installed `pyethapp` inside a virtualenv

## System/environment
- OS: Fedora 25
- python version: 2.7.13
- pyethapp version: 1.5.0? (where to check? "pip freeze" doesn't show version, can't launch pyethapp, or run "pyethapp --version", don't see in docs)
- installation method (pip & pypi/git & setup.py): git & pip install (from [getting started guide](https://github.com/ethereum/pyethapp/wiki/Getting-Started))
- pyethapp branch: develop

## Expected behaviour
```bash
$: pyethapp
```
-> should launch pyethapp

## Observed behaviour
pyethapp won't launch
this appears to be a [bug in the openssl library](https://github.com/shadowsocks/shadowsocks/issues/646#) which may have been addressed in debian/ubuntu-based distros.  Error output below:

Traceback (most recent call last):
  File "/.../pyethapp/.venv/bin/pyethapp", line 11, in <module>
    load_entry_point('pyethapp', 'console_scripts', 'pyethapp')()
  File "/.../pyethapp/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/.../pyethapp/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2649, in load_entry_point
    return ep.load()
  File "/.../pyethapp/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2303, in load
    return self.resolve()
  File "/.../pyethapp/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/.../pyethapp/pyethapp/app.py", line 15, in <module>
    from devp2p.app import BaseApp
  File "/.../pyethapp/.venv/lib/python2.7/site-packages/devp2p/app.py", line 8, in <module>
    from devp2p import crypto
  File "/.../pyethapp/.venv/lib/python2.7/site-packages/devp2p/crypto.py", line 7, in <module>
    import pyelliptic
  File "/.../pyethapp/.venv/lib/python2.7/site-packages/pyelliptic/__init__.py", line 43, in <module>
    from .openssl import OpenSSL
  File "/.../pyethapp/.venv/lib/python2.7/site-packages/pyelliptic/openssl.py", line 310, in <module>
    OpenSSL = _OpenSSL(libname)
  File "/.../pyethapp/.venv/lib/python2.7/site-packages/pyelliptic/openssl.py", line 144, in __init__
    self.EVP_CIPHER_CTX_reset = self._lib.EVP_CIPHER_CTX_reset
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 370, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 375, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
**AttributeError: /lib64/libcrypto.so.10: undefined symbol: EVP_CIPHER_CTX_reset**

## Steps to reproduce
Install Fedora 25, follow [getting started guide](https://github.com/ethereum/pyethapp/wiki/Getting-Started) (also installing, where needed, gcc, python-devel, libevent-del, redhat-rpm-config, gcc-c++, and openssl-devel; not certain that all of these needed to be installed, or weren't stock) ,
finally, run  `pyethapp`

**Comment by artas728** [comment]
Hi
I have the same problem. 
I would be grateful for your help

**Comment by cwirz** [comment]
Having the same problem...

**Comment by cwirz** [comment]
running `pip install pyelliptic==1.5.7` fixed this issue for me

**Comment by koreymacdougall** [comment]
excellent!  thanks for the tip @cwirz
