### ISSUE TITLE
Problem during pyethapp compilation and pickle

### ISSUE THREAD

**Issue by ogonbat** [ethereum/pyethapp#243]
## Checklist
- [ ] installed HomeBrew
- [ ] installed HomeBrew dependencies
- [ ] installed HomeBrew Python

## System/environment

- OS: MC OSX Sierra
- python version: 2.7.13
- pyethapp version: GITHUB clone
- installation method (pip & pypi/git & setup.py): USE_PYETHEREUM_DEVELOP=1 python setup.py develop

## Observed behaviour
`Traceback (most recent call last):
  File "setup.py", line 97, in <module>
    '''
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/Andrea/Documents/Ether/ether/lib/python2.7/site-packages/setuptools/command/develop.py", line 36, in run
    self.install_for_development()
  File "/Users/Andrea/Documents/Ether/ether/lib/python2.7/site-packages/setuptools/command/develop.py", line 150, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/Users/Andrea/Documents/Ether/ether/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 746, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/Users/Andrea/Documents/Ether/ether/lib/python2.7/site-packages/pkg_resources/__init__.py", line 852, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/Users/Andrea/Documents/Ether/ether/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1124, in best_match
    return self.obtain(req, installer)
  File "/Users/Andrea/Documents/Ether/ether/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1136, in obtain
    return installer(requirement)
  File "/Users/Andrea/Documents/Ether/ether/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Users/Andrea/Documents/Ether/ether/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 699, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/Andrea/Documents/Ether/ether/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 880, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/Andrea/Documents/Ether/ether/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1119, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/Andrea/Documents/Ether/ether/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1105, in run_setup
    run_setup(setup_script, args)
  File "/Users/Andrea/Documents/Ether/ether/lib/python2.7/site-packages/setuptools/sandbox.py", line 257, in run_setup
    raise
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/Andrea/Documents/Ether/ether/lib/python2.7/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/Andrea/Documents/Ether/ether/lib/python2.7/site-packages/setuptools/sandbox.py", line 170, in save_modules
    saved_exc.resume()
  File "/Users/Andrea/Documents/Ether/ether/lib/python2.7/site-packages/setuptools/sandbox.py", line 144, in resume
    type, exc = map(pickle.loads, self._saved)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1139, in load_reduce
    value = func(*args)
TypeError: __init__() takes at least 3 arguments (1 given)`

## Steps to reproduce
clone pyethapp from github
setup develop

**Comment by browning** [comment]
I hit the same issue, `brew install autoconf` and then `brew link autoconf` fixed it for me
