### ISSUE TITLE
Pyethapp installs but errors on run: symbol not found

### ISSUE THREAD

**Issue by tatianafrank** [ethereum/pyethapp#249]
- installed `pyethapp` directly on osx
- python version: 2.7
- installation method: pip
-pyethapp version: 1.5

Pytheapp is installed successfully but trying to run any command, even just 'pyethapp' results in the below error stack trace: 

`Traceback (most recent call last):
  File "/Users/tatianafrank/anaconda/bin/pyethapp", line 7, in <module>
    from pyethapp.app import app
  File "/Users/tatianafrank/anaconda/lib/python2.7/site-packages/pyethapp/app.py", line 15, in <module>
    from devp2p.app import BaseApp
  File "/Users/tatianafrank/anaconda/lib/python2.7/site-packages/devp2p/app.py", line 8, in <module>
    from devp2p import crypto
  File "/Users/tatianafrank/anaconda/lib/python2.7/site-packages/devp2p/crypto.py", line 16, in <module>
    import pyelliptic
  File "/Users/tatianafrank/anaconda/lib/python2.7/site-packages/pyelliptic/__init__.py", line 43, in <module>
    from .openssl import OpenSSL
  File "/Users/tatianafrank/anaconda/lib/python2.7/site-packages/pyelliptic/openssl.py", line 310, in <module>
    OpenSSL = _OpenSSL(libname)
  File "/Users/tatianafrank/anaconda/lib/python2.7/site-packages/pyelliptic/openssl.py", line 144, in __init__
    self.EVP_CIPHER_CTX_reset = self._lib.EVP_CIPHER_CTX_reset
  File "/Users/tatianafrank/anaconda/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/Users/tatianafrank/anaconda/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x1003c40c0, EVP_CIPHER_CTX_reset): symbol not found`

**Comment by leonid-ed** [comment]
I have the same problem with pyethapp.

It looks like this issue is similar to #234 
But when I made `pip install pyelliptic==1.5.7` and tried to start `pyethapp` I got an error:
> Traceback (most recent call last):
>   File "/home/leonid/.virtualenvs/pyethapp_env/bin/pyethapp", line 7, in <module>
>     from pyethapp.app import app
>   File "/home/leonid/.virtualenvs/pyethapp_env/local/lib/python2.7/site-packages/pyethapp/app.py", line 19, in <module>
>     from ethereum import blocks

**Comment by buckysballs** [comment]
I'm affected by this as well, digging in.

**Comment by reinka** [comment]
@leonid-ed  The error is thrown because the file in the `ethereum` package is actually called `block` and not `blocks`. 

I could fix this issue by installing the development version of `pyethapp` as described [ in their README here](https://github.com/ethereum/pyethapp#development-version). 

So the whole procedure to fix this `symbol not found` error was for me:

1. Downgrading `pyelliptic` via `pip install pyelliptic==1.5.7`
2. Install `pyethapp` development version as described in the link above.

(You could probably also mess with the `import` statement and change it to `block` thought this approach is not recommended.)
