### ISSUE TITLE
Numerous errors after a fresh pyethapp install

### ISSUE THREAD

**Issue by ckepper** [ethereum/pyethapp#25]
After installing pyethapp on my machine for the first time I received a couple of errors. As I am new to pyethereum I may have made an installation error. 

I use Mac OS X 10.10.4 with Python 2.7.10 in a virtualenv.

At least one of those errors was already reported elsewhere (e.g. ethereum/pyethereum#259 `TypeError: function takes exactly 2 arguments (1 given)`) so I won't repeat it. After this error a couple more errors occurred:

## Peer not ready
```python 
Traceback (most recent call last):
  File "/Users/kepper/.virtualenvs/ethereum/lib/python2.7/site-packages/gevent-1.1a1-py2.7-macosx-10.10-x86_64.egg/gevent/greenlet.py", line 368, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/kepper/.virtualenvs/ethereum/lib/python2.7/site-packages/devp2p-0.4.1-py2.7.egg/devp2p/peer.py", line 201, in _run_ingress_message
    gevent.socket.wait_read(self.connection.fileno())
  File "<string>", line 1, in fileno
  File "/Users/kepper/.virtualenvs/ethereum/lib/python2.7/site-packages/gevent-1.1a1-py2.7-macosx-10.10-x86_64.egg/gevent/_socket2.py", line 37, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
<Peer('not ready',) > failed with error
```

## Exception: no protocol for id 16
```python 
Traceback (most recent call last):
  File "/Users/kepper/.virtualenvs/ethereum/lib/python2.7/site-packages/gevent-1.1a1-py2.7-macosx-10.10-x86_64.egg/gevent/greenlet.py", line 368, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/kepper/.virtualenvs/ethereum/lib/python2.7/site-packages/devp2p-0.4.1-py2.7.egg/devp2p/peer.py", line 193, in _run_decoded_packets
    self._handle_packet(self.mux.packet_queue.get())  # get_packet blocks
  File "/Users/kepper/.virtualenvs/ethereum/lib/python2.7/site-packages/devp2p-0.4.1-py2.7.egg/devp2p/peer.py", line 163, in _handle_packet
    protocol, cmd_id = self.protocol_cmd_id_from_packet(packet)
  File "/Users/kepper/.virtualenvs/ethereum/lib/python2.7/site-packages/devp2p-0.4.1-py2.7.egg/devp2p/peer.py", line 159, in protocol_cmd_id_from_packet
    raise Exception('no protocol for id %s' % packet.cmd_id)
Exception: no protocol for id 16
<Greenlet at 0x1092f8b90: <bound method Peer._run_decoded_packets of <Peer('92.51.165.126', 30303) ++eth-v0.9.28-35412971/Gav's Node>>> failed with Exception
```

## AssertionError: assert remote != self.this_node
```python
Traceback (most recent call last):
  File "/Users/kepper/.virtualenvs/ethereum/lib/python2.7/site-packages/gevent-1.1a1-py2.7-macosx-10.10-x86_64.egg/gevent/greenlet.py", line 368, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/kepper/.virtualenvs/ethereum/lib/python2.7/site-packages/gevent-1.1a1-py2.7-macosx-10.10-x86_64.egg/gevent/baseserver.py", line 133, in _close_when_done
    return handle(*args)
  File "/Users/kepper/.virtualenvs/ethereum/lib/python2.7/site-packages/devp2p-0.4.1-py2.7.egg/devp2p/discovery.py", line 564, in _handle_packet
    self.receive(address, message)
  File "/Users/kepper/.virtualenvs/ethereum/lib/python2.7/site-packages/devp2p-0.4.1-py2.7.egg/devp2p/discovery.py", line 558, in receive
    self.protocol.receive(address, message)
  File "/Users/kepper/.virtualenvs/ethereum/lib/python2.7/site-packages/devp2p-0.4.1-py2.7.egg/devp2p/discovery.py", line 322, in receive
    cmd(nodeid, payload, mdc)
  File "/Users/kepper/.virtualenvs/ethereum/lib/python2.7/site-packages/devp2p-0.4.1-py2.7.egg/devp2p/discovery.py", line 415, in recv_pong
    self.kademlia.recv_pong(node, echoed)
  File "/Users/kepper/.virtualenvs/ethereum/lib/python2.7/site-packages/devp2p-0.4.1-py2.7.egg/devp2p/kademlia.py", line 516, in recv_pong
    assert remote != self.this_node
AssertionError
<Greenlet at 0x109327eb0: _close_when_done("\x11+!n\x97\xad\x00\x1eL$\x00\x98\xb4\xd5\xc9\xcb, ('127.0.0.1', 30303))> failed with AssertionError
```

Thank you for your help.

**Comment by ckepper** [comment]
Bummer. Seems like I was missing [ethereum/pyrlp](//github.com/ethereum/pyrlp) and [ethereum/pydevp2p](//github.com/ethereum/pydevp2p). After I installed both, everything worked fine.
