### ISSUE TITLE
ImportError: cannot import name blocks

### ISSUE THREAD

**Issue by yuyuyuyuyuyuyuyuyu** [ethereum/pyethapp#257]
$ pyethapp run
Traceback (most recent call last):
  File "/usr/local/bin/pyethapp", line 7, in <module>
    from pyethapp.app import app
  File "/usr/local/lib/python2.7/dist-packages/pyethapp/app.py", line 19, in <module>
    from ethereum import blocks
ImportError: cannot import name blocks

**Comment by adithyabhatkajake** [comment]
Installing [ethereum==1.6.0] in pip solved this for me.

**Comment by rainysiu** [comment]
from ethereum import blocks
ImportError: cannot import name blocks

how to solve this problem?

**Comment by MareoRaft** [comment]
Yes, `sudo python2.7 /usr/local/bin/pip install ethereum==1.6.0` solved *this problem* for me too, although it brings up a similar error now: `ImportError: No module named tinyrpc.protocols.jsonrpc`.  Not to mention that the current version of ethereum is 2.3.0, so 1.6.0 feels quite old.

**Comment by vihanggodbole** [comment]
Did anyone solve this?
