### ISSUE TITLE
AttributeError: dlsym(0x7fdd104666a0, EVP_CIPHER_CTX_reset): symbol not found

### ISSUE THREAD

**Issue by Sitin** [ethereum/pyethapp#258]
## Checklist
- [x] installed `pyethapp` inside a virtualenv

## System/environment

- OS: OS X 10.12.6
- python version: 2.7.13 (by Homebrew)
- pyethapp version: 1.5.0
- installation method (pip & pypi/git & setup.py): pip

## Build dependencies
`automake`, `libtool`, `pkg-config`, `libffi`, `gmp`, `openssl` installed by Homebrew with default parameters and has latest versions:

```sh
$ brew upgrade automake libtool pkg-config libffi gmp openssl
Error: automake 1.15.1 already installed
Error: libtool 2.4.6_1 already installed
Error: pkg-config 0.29.2 already installed
Error: libffi 3.2.1 already installed
Error: gmp 6.1.2 already installed
Error: openssl 1.0.2l already installed
```

## Expected behaviour
Run without failure.

## Observed behaviour
Failed to run. Exits with error:
```sh
$ pyethapp
Traceback (most recent call last):
  File "/Users/sitin/.virtualenv/crypto/bin/pyethapp", line 7, in <module>
    from pyethapp.app import app
  File "/Users/sitin/.virtualenv/crypto/lib/python2.7/site-packages/pyethapp/app.py", line 15, in <module>
    from devp2p.app import BaseApp
  File "/Users/sitin/.virtualenv/crypto/lib/python2.7/site-packages/devp2p/app.py", line 8, in <module>
    from devp2p import crypto
  File "/Users/sitin/.virtualenv/crypto/lib/python2.7/site-packages/devp2p/crypto.py", line 16, in <module>
    import pyelliptic
  File "/Users/sitin/.virtualenv/crypto/lib/python2.7/site-packages/pyelliptic/__init__.py", line 43, in <module>
    from .openssl import OpenSSL
  File "/Users/sitin/.virtualenv/crypto/lib/python2.7/site-packages/pyelliptic/openssl.py", line 310, in <module>
    OpenSSL = _OpenSSL(libname)
  File "/Users/sitin/.virtualenv/crypto/lib/python2.7/site-packages/pyelliptic/openssl.py", line 144, in __init__
    self.EVP_CIPHER_CTX_reset = self._lib.EVP_CIPHER_CTX_reset
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fdd104666a0, EVP_CIPHER_CTX_reset): symbol not found
```

## Steps to reproduce
Install to a clean virtual environment and execute `pyethapp`.

**Comment by camelportlogistics** [comment]
Encountered the same issue. Tried rolling back pyelliptic version to 1.5.7, which produced the following issue

(https://github.com/ethereum/pyethapp/issues/257)

**Comment by lrettig** [comment]
Me too. Appears to be a duplicate of #249.
