### ISSUE TITLE
wrong behaviour at startup__raise VersionConflict(dist, req).with_context(dependent_req) pkg_resources.ContextualVersionConflict: (rlp 0.6.0 (/sba/Ethereum/pyethapp/.venv/lib/python2.7/site-packages), Requirement.parse('rlp<0.6.0,>=0.5.1'), set(['devp2p']))

### ISSUE THREAD

**Issue by souleb** [ethereum/pyethapp#259]
## Checklist
- [ +] installed `pyethapp` inside a virtualenv

## System/environment

- OS: 16.04.2-Ubuntu 
- python version: Python 2.7.12
- pyethapp version: 1.5.0
- installation method (pip & pypi/git & setup.py): pip & git

## Expected behaviour
(.venv) ~/ethereum/pyethapp/$ pyethapp
Usage: pyethapp [OPTIONS] COMMAND [ARGS]...

  Welcome to ethapp version...

Options:
[…]

## Observed behaviour
(.venv) ~/Ethereum/pyethapp$ pyethapp
Traceback (most recent call last):
  File "/sba/Ethereum/pyethapp/.venv/bin/pyethapp", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/sba/Ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/sba/Ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3122, in _call_aside
    f(*args, **kwargs)
  File "/sba/Ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/sba/Ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/sba/Ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 679, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/sba/Ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (rlp 0.6.0 (/sba/Ethereum/pyethapp/.venv/lib/python2.7/site-packages), Requirement.parse('rlp<0.6.0,>=0.5.1'), set(['devp2p']))

**Comment by pglezen** [comment]
This is probably a duplicate of issue #253.

If you change your `requirements.txt` as specified in this pull request, you might be fine.

<https://github.com/ethereum/pyethapp/pull/255/files>

I followed Matsulib's tip by uninstalling `rlp` and installing a back-level version along with the required websocket libraries.

```
pip install rlp==-0.5.1
pip install prat-geventwebsocket
```
Then I was able to start the `pyethapp` client successfully.
