### ISSUE TITLE
ImportError: No module named refcount_db

### ISSUE THREAD

**Issue by skoeners** [ethereum/pyethapp#26]
I have cloned and attempted to run pyethapp according to the instructions on GitHub on my MacBook and get the following error when attempting to run:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/pyethapp", line 9, in <module>
    load_entry_point('pyethapp==0.9.18', 'console_scripts', 'pyethapp')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyethapp-0.9.18-py2.7.egg/pyethapp/app.py", line 15, in <module>
    from eth_service import ChainService
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyethapp-0.9.18-py2.7.egg/pyethapp/eth_service.py", line 12, in <module>
    from ethereum.refcount_db import RefcountDB
ImportError: No module named refcount_db

I can see ethereum has other modules but no refcount_db module. Is this a bug?

**Comment by heikoheiko** [comment]
updated the ethereum pypi package, should work now if you do a fresh install
