### ISSUE TITLE
loadchain.py in examples does not work

### ISSUE THREAD

**Issue by bgits** [ethereum/pyethapp#264]
## Checklist
- [X ] installed `pyethapp` inside a virtualenv

## System/environment

- OS: FIXME
- python version: Python 2.7.13
- pyethapp version: 1.5.0
- installation method (pip & pypi/git & setup.py): git clone && USE_PYETHEREUM_DEVELOP=1 python setup.py develop
- pyethapp branch (if applicable): develop

## Expected behaviour
should read all block in the chain and print the blk.header.number

## Observed behaviour
  File "loadchain.py", line 62, in <module>
    chain = get_chain()
  File "loadchain.py", line 18, in get_chain
    return Chain(Env(db))
  File "/Users/anaconda/envs/pyethapp/lib/python2.7/site-packages/ethereum-2.0.4-py2.7.egg/ethereum/pow/chain.py", line 47, in __init__
    elif "extraData" in genesis:
TypeError: argument of type 'Env' is not iterable

Moved past this error by setting `genesis = genesis.config` but then ran in to the next error

  File "loadchain.py", line 62, in <module>
    chain = get_chain()
  File "loadchain.py", line 18, in get_chain
    return Chain(Env(db))
  File "/Users/anaconda/envs/pyethapp/lib/python2.7/site-packages/ethereum-2.0.4-py2.7.egg/ethereum/pow/chain.py", line 68, in __init__
    }, self.env)
  File "/Users/anaconda/envs/pyethapp/lib/python2.7/site-packages/ethereum-2.0.4-py2.7.egg/ethereum/genesis_helpers.py", line 118, in mk_basic_state
    addr = normalize_address(addr)
  File "/Users/anaconda/envs/pyethapp/lib/python2.7/site-packages/ethereum-2.0.4-py2.7.egg/ethereum/utils.py", line 220, in normalize_address
    raise Exception("Invalid address format: %r" % x)
Exception: Invalid address format: 'ACCOUNT_INITIAL_NONCE'

## Steps to reproduce
cd examples && python loadchain.py

**Comment by cmaliwal** [comment]
@bgits you are right sir.
```

>>> from ethereum.ethpow import check_pow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ethpow
>>> from ethereum.chain import Chain
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named chain
```

**Comment by bgits** [comment]
I discovered after opening this issue that pyethapp just no longer works with the current chain.

**Comment by cmaliwal** [comment]
what is the substitute of this ?

**Comment by cmaliwal** [comment]
You created this issue on 16 Oct .

I think, Author or contributor have to look on this .

**Comment by bgits** [comment]
It seems the entire project is being replaced by:
https://github.com/ethereum/py-evm

Have not had time to investigate if py-evm is in a working state yet. If it
is this ticket should be updated to start using py-evm.

**Comment by cmaliwal** [comment]
Thanks for the update.

Yes, looks like `py-evm` is  in developing mode and I am also not sure `py-evm` is in a working state or not.

**Comment by step21** [comment]
Afaik you are correct that it is not properly being developed/maintained anymore, but it is definitely not being replaced by py-evm. Pyethapp was a full client, py-evm is just an evm implementation so if anything it is more likely to replace pyethereum as mentioned in its readme.
