### ISSUE TITLE
DistributionNotFound: The 'ethereum==2.1.1' distribution was not found and is required by pyethapp

### ISSUE THREAD

**Issue by ivanemoje** [ethereum/pyethapp#276]
## Checklist
- [x] installed `pyethapp` inside a virtualenv
DONE
## System/environment

- OS: UBUNTU 16.04 Xenial
- python version: 2.7
- pyethapp version: 1.5.1a0
- installation method (pip & pypi/git & setup.py): pip
- pyethapp branch (if applicable): N/A

## Expected behaviour
pyethapp

## Observed behaviour
```
$ pyethapp
Traceback (most recent call last):
  File "/home/user/.virtualenvs/pyethapp/bin/pyethapp", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/user/.virtualenvs/pyethapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3144, in <module>
    @_call_aside
  File "/home/user/.virtualenvs/pyethapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3128, in _call_aside
    f(*args, **kwargs)
  File "/home/user/.virtualenvs/pyethapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3157, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/user/.virtualenvs/pyethapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/home/user/.virtualenvs/pyethapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/user/.virtualenvs/pyethapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ethereum==2.1.1' distribution was not found and is required by pyethapp
```
## Steps to reproduce

sudo USE_PYETHEREUM_DEVELOP=1 python setup.py develop
pyethapp

**Comment by kachar** [comment]
I'm having the same issue.

When I try to install it via pip it goes:

```
$ pip install ethereum==2.1.1
Collecting ethereum==2.1.1
  Using cached ethereum-2.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    error in ethereum setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-SuNVRN/ethereum/
(pyethapp)
```

I was able to install the package via `pip3` but this does not affect the `pyethapp` run and same error is triggered

Issue seems to come from the empty dependency list at https://github.com/ethereum/pyethereum/blob/develop/setup.py#L36

**Comment by gpathela** [comment]
@kachar : Have you find any solution for this problem

**Comment by rainysiu** [comment]
Running ethereum-2.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-XvygQK/ethereum-2.1.1/egg-dist-tmp-HR1gl6
error: Setup script exited with error in ethereum setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed

**Comment by mezrin** [comment]
Oh my god. Finally, update your lib to the latest python and latest dependencies.
It is so...  need to be done

This is a solution for the error above:
https://stackoverflow.com/questions/47753737/pyethapp-installation-issue-on-osx-10-13-2

**Comment by ivanemoje** [comment]
Thanks @mezrin for pointing to solution. After running `pip install setuptools==37` I am now able to complete installation.

**Comment by RorschachRev** [comment]
pip install setuptools==37:
  Downloading setuptools-37.0.0-py2.py3-none-any.whl (481kB)
    100% |████████████████████████████████| 491kB 540kB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 38.5.1
    Uninstalling setuptools-38.5.1:
      Successfully uninstalled setuptools-38.5.1
Successfully installed setuptools-37.0.0

Installation after *downgrading* setuptools was able to succeed. This isn't a long term solution since ethereum foundation is relying on a bug that was later resolved.

**Comment by vesellov** [comment]
Hi Guys... I am now getting such error on Ubuntu with python 2.7.14 : 

`veselinux@datahaven:/tmp$ ./venv2714/bin/pip install pyethapp
Collecting pyethapp
  Using cached https://files.pythonhosted.org/packages/58/f3/a0120ca69af0d7bd2e8728c07ddf5fccc6250fe4cb2980c303e30b7a6d4f/pyethapp-1.5.0-py2.py3-none-any.whl
Collecting click (from pyethapp)
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting CodernityDB (from pyethapp)
  Using cached https://files.pythonhosted.org/packages/fb/14/ab1cdd890e93d4bb916fff9ea7482b88f1b4409e524cec5ec55188dd422a/CodernityDB-0.5.0.tar.gz
Collecting scrypt (from pyethapp)
  Using cached https://files.pythonhosted.org/packages/01/6f/3c8dd0f18f73ceddfbdd606c0c895ebb66748606682d77da3743c7c0c56f/scrypt-0.8.6.tar.gz
Collecting leveldb (from pyethapp)
  Using cached https://files.pythonhosted.org/packages/ec/c1/ca3b4199bd4073e6430076f1edd8061f2f548e831eeddc3cbc077ebaa0ca/leveldb-0.194.tar.gz
Collecting werkzeug (from pyethapp)
  Using cached https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl
Collecting requests (from pyethapp)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting statistics (from pyethapp)
  Using cached https://files.pythonhosted.org/packages/bb/3a/ae99a15e65636559d936dd2159d75af1619491e8cb770859fbc8aa62cef6/statistics-1.0.3.5.tar.gz
Collecting devp2p>=0.8.0 (from pyethapp)
  Using cached https://files.pythonhosted.org/packages/be/69/80f0122014bac80e669960be46ea916bb8c062a203125917c43a49eba97f/devp2p-0.9.3.tar.gz
    Complete output from command python setup.py egg_info:
    
    Link to http://pypi.python.org/simple/pytest-runner/ ***BLOCKED*** by --allow-hosts
    
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    
    Link to http://pypi.python.org/simple/ ***BLOCKED*** by --allow-hosts
    
    No local packages or download links found for pytest-runner>2.0,<3
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Sbuf_X/devp2p/setup.py", line 56, in <module>
        tests_require=test_requirements
      File "/tmp/python2_7_14/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/venv2714/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/tmp/venv2714/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/dist.py", line 245, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/tmp/venv2714/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 576, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/tmp/venv2714/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 821, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/tmp/venv2714/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 833, in obtain
        return installer(requirement)
      File "/tmp/venv2714/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/dist.py", line 294, in fetch_build_egg
        return cmd.easy_install(req)
      File "/tmp/venv2714/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/easy_install.py", line 583, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner>2.0,<3')`


I also installed `setuptools==37` first ....

**Comment by vesellov** [comment]
okay.... looks like that project is dead and community is working on py-evm : https://github.com/ethereum/py-evm
