### ISSUE TITLE
Error in starting pyethapp

### ISSUE THREAD

**Issue by Gujjar95** [ethereum/pyethapp#283]
## Checklist
- [ ok] installed `pyethapp` inside a virtualenv

## System/environment

- OS: ubuntu 16.04 LTS
- python version: 2.7(for this)
- installation method (pip & pypi/git & setup.py): pip
- pyethapp branch (if applicable): no

## Expected behaviour
should return all available commands

## Observed behaviour
`Traceback (most recent call last):
  File "/home/gujjar/pyethapp/bin/pyethapp", line 7, in <module>
    from pyethapp.app import app
  File "/home/gujjar/pyethapp/local/lib/python2.7/site-packages/pyethapp/app.py", line 19, in <module>
    from ethereum import blocks
ImportError: cannot import name blocks
`

**Comment by Forz4** [comment]
i have got the same error = =

**Comment by daggerhashimoto** [comment]
same here

**Comment by gewuxy** [comment]
same here

**Comment by pranithkumar** [comment]
pip install pyethapp==1.5.1a0

This worked for me

**Comment by bigbigtooth** [comment]
me too, uninstall the pip default version, and run "pip install pyethapp==1.5.1a0" , it works !!!

**Comment by Jianbo-Gao** [comment]
me too,
```
pip uninstall pyethapp
pip install pyethapp==1.5.1a0
```
and it works!

**Comment by opheelia** [comment]
Same problem here and "pip install pyethapp==1.5.1a0" also solved the problem. Thanks!
