### ISSUE TITLE
pip install problems

### ISSUE THREAD

**Issue by MikeTam1021** [ethereum/pyethapp#287]
Not sure who tried the pip install. It is not working correctly on my system. Here is a screen shot of the error. MacOS High Sierra 10.13.2.

I'm a good programmer, I could probably fix this myself but I am new to cryptocurrencies and feel it is a better use of my time to survey the landscape than fix bugs. Would like this issue to be resolved before I invest more time in learning this framework

<img width="573" alt="screen shot 2018-03-04 at 2 24 07 pm" src="https://user-images.githubusercontent.com/7306740/36950191-02283412-1fb8-11e8-95fb-948c05a3f005.png">

**Comment by FrancisJen** [comment]
I have the same problem

**Comment by ghost** [comment]
I have this error as well

**Comment by arseneeth** [comment]
same issue, any updates? have someone solved it?

**Comment by sbeaumont** [comment]
Same here. install is broken on mac...?

**Comment by DronyPandey** [comment]
To state the cliche - I too have the same problem. Checked the python version - it is 3.6 all right. It appears that the install is indeed broken. The only thing I can point out is that the error that I get is during a different collect module - 

```
Collecting gipc==0.4.0 (from pyethapp)
  Using cached https://files.pythonhosted.org/packages/df/68/317f273ecff80ab2df856fab40d218b64674e7b043182235c7e9e8b49244/gipc-0.4.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xr/nxn_0kk17yq962z9rxhxfctr0000gn/T/pip-install-h5k0t_mw/gipc/setup.py", line 22, in <module>
        long_description=open("README.rst").read().decode('utf-8'),
    AttributeError: 'str' object has no attribute 'decode'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /
/private/var/folders/xr/nxn_0kk17yq962z9rxhxfctr0000gn/T/pip-install-h5k0t_mw/gipc/

```
It could be an issue in the script where the directory `nxn_0kk17yq962z9rxhxfctr0000gn/T/pip-install-h5k0t_mw/gipc/` has not been created as I could navigate up to `/private/var/folders/xr`

**Comment by maxhallhatesm3** [comment]
@MikeTam1021 @FrancisJen @HenrikMoe @arsenyjin @sbeaumont @DronyPandey 

Did a solution ever come about for this issue?  It continues for me, I detailed my errors in my new issue ticket #298.

Is there a lack of pyethapp support due to the rising prominence of py-evm?
