### ISSUE TITLE
pyethapp installation problems.

### ISSUE THREAD

**Issue by maxhallhatesm3** [ethereum/pyethapp#298]
## Checklist
- [X] installed `pyethapp` inside a virtualenv

## System/environment

- OS: Linux ubuntu 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- python version: Python 2.7.15rc1
- pyethapp version: N/A
- installation method (pip & pypi/git & setup.py): pip, pip3, and clone dev vers. from Git.
- pyethapp branch (if applicable): N/A

## Expected behaviour
Successful installation.

## Observed behaviour
pip install:
> Downloading https://files.pythonhosted.org/packages/56/00/a2e4412d8e863afb53c4f799e484c748577d4f8f0e5dd7d6f1137637a964/eth-hash-0.1.4.tar.gz
eth-hash requires Python '>=3.5, <4' but the running Python is 2.7.15

build from dev vers.:
> scrypt-1.2.1/libcperciva/crypto/crypto_aes.c:6:10: fatal error: openssl/aes.h: No such file or directory
 #include <openssl/aes.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

## Steps to reproduce
sudo apt-get install build-essential automake pkg-config libtool libffi-dev libgmp-dev

sudo apt install python-pip

pip install virtualenv virtualenvwrapper

source `which virtualenvwrapper.sh`

mkvirtualenv pyethapp

sudo apt install git

git clone https://github.com/ethereum/pyethapp

cd pyethapp

sudo USE_PYETHEREUM_DEVELOP=1 python setup.py develop

ERR: scrypt-1.2.1/libcperciva/crypto/crypto_aes.c:6:10: fatal error: openssl/aes.h: No such file or directory
 #include <openssl/aes.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

pip install pyethapp

ERR: Downloading https://files.pythonhosted.org/packages/56/00/a2e4412d8e863afb53c4f799e484c748577d4f8f0e5dd7d6f1137637a964/eth-hash-0.1.4.tar.gz
eth-hash requires Python '>=3.5, <4' but the running Python is 2.7.15

**Comment by maxhallhatesm3** [comment]
Brickwall on **Ubuntu 14.04 x86 64-bit** is as follows:

>sudo apt purge python2.7
>sudo apt purge python2.7-minimal
>pip3 install virtualenv 
>pip3 install virtualenvwrapper
>source `which virtualenvwrapper.sh`
>mkvirtualenv asdf1234
>pip3 install pyethapp

_after error; also tried:_
1. pip3 install gipc
2. pip3 install --upgrade setuptools
3. sudo apt-get install libmysqlclient-dev

Error persists:
```
.....Collecting werkzeug (from pyethapp)
  Using cached https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl
Collecting click (from pyethapp)
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting ethereum>=1.5.1 (from pyethapp)
  Using cached https://files.pythonhosted.org/packages/ca/48/bd2484ff00fad56bfabad46af8d91f0ab4c6844e389e00b00c7609b405e0/ethereum-2.3.2.tar.gz
Collecting ipython<5.0.0,>=3.0.0 (from pyethapp)
  Using cached https://files.pythonhosted.org/packages/f0/b7/c801138e58df6ef9fd47bd2d7eed32ab0b47df22929c53e142f96d2247c5/ipython-4.2.1-py3-none-any.whl
Collecting leveldb (from pyethapp)
  Using cached https://files.pythonhosted.org/packages/ec/c1/ca3b4199bd4073e6430076f1edd8061f2f548e831eeddc3cbc077ebaa0ca/leveldb-0.194.tar.gz
Collecting pbkdf2 (from pyethapp)
  Using cached https://files.pythonhosted.org/packages/02/c0/6a2376ae81beb82eda645a091684c0b0becb86b972def7849ea9066e3d5e/pbkdf2-1.3.tar.gz
Collecting gipc==0.4.0 (from pyethapp)
  Using cached https://files.pythonhosted.org/packages/df/68/317f273ecff80ab2df856fab40d218b64674e7b043182235c7e9e8b49244/gipc-0.4.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6896n62a/gipc/setup.py", line 22, in <module>
        long_description=open("README.rst").read().decode('utf-8'),
    AttributeError: 'str' object has no attribute 'decode'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-6896n62a/gipc/
```

**Comment by maxhallhatesm3** [comment]
Brickwall on **macOS 10.13.3 (17D102)** is as follows:

>brew install automake libtool pkg-config libffi gmp openssl
>pip3 install virtualenv 
>pip3 install virtualenvwrapper
>source `which virtualenvwrapper.sh`
>mkvirtualenv asdf1234
>pip3 install pyethapp

Error:
```
.....Collecting gevent==1.1.0 (from pyethapp)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/0f/90/4c77e7bace6ce72123bcadbf385ef466c7237846fbef03f786eaad4f84e6/gevent-1.1.0.tar.gz (2.0MB)
    100% |████████████████████████████████| 2.0MB 13.2MB/s 
Collecting ethereum>=1.5.1 (from pyethapp)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/ca/48/bd2484ff00fad56bfabad46af8d91f0ab4c6844e389e00b00c7609b405e0/ethereum-2.3.2.tar.gz
Collecting lmdb (from pyethapp)
  Downloading https://files.pythonhosted.org/packages/cb/31/5be8f436b56733d9e69c721c358502f4d77b627489a459978686be7db65f/lmdb-0.94.tar.gz (4.0MB)
    100% |████████████████████████████████| 4.0MB 4.9MB/s 
Collecting rlp>=0.4.4 (from pyethapp)
  Downloading https://files.pythonhosted.org/packages/b4/dc/a54b93cac06f46ef49b8da6cb06a6bf77ba65bf45dec5c498f51ceefc5c6/rlp-1.0.1-py2.py3-none-any.whl
Requirement already satisfied: wheel in ./.virtualenvs/CUPHEAD/lib/python3.6/site-packages (from pyethapp) (0.31.1)
Collecting pexpect (from pyethapp)
  Downloading https://files.pythonhosted.org/packages/89/e6/b5a1de8b0cc4e07ca1b305a4fcc3f9806025c1b651ea302646341222f88b/pexpect-4.6.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 17.8MB/s 
Collecting gipc==0.4.0 (from pyethapp)
  Downloading https://files.pythonhosted.org/packages/df/68/317f273ecff80ab2df856fab40d218b64674e7b043182235c7e9e8b49244/gipc-0.4.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7n/jc7wqsqs3t50pbt2p1z_c1rm0000gp/T/pip-install-4imzl5u0/gipc/setup.py", line 22, in <module>
        long_description=open("README.rst").read().decode('utf-8'),
    AttributeError: 'str' object has no attribute 'decode'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7n/jc7wqsqs3t50pbt2p1z_c1rm0000gp/T/pip-install-4imzl5u0/gipc/
```
