### ISSUE TITLE
AttributeError while installing with python 3.4

### ISSUE THREAD

**Issue by npcode** [ethereum/pyethapp#61]
Here is the error:

```
$ python setup.py install

...

Running gipc-0.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-m3ex07jz/gipc-0.4.0/egg-dist-tmp-iczjzu8e
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 237, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 267, in run
    return func()
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 236, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-m3ex07jz/gipc-0.4.0/setup.py", line 22, in <module>
    
AttributeError: 'str' object has no attribute 'decode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 74, in <module>
    '''
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.4/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3.4/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 389, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 619, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 670, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 718, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 836, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1081, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1093, in obtain
    return installer(requirement)
  File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 638, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 668, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 851, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1079, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1065, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 240, in run_setup
    raise
  File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 164, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 139, in resume
    compat.reraise(type, exc, self._tb)
  File "/usr/lib/python3.4/site-packages/setuptools/compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 237, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 267, in run
    return func()
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 236, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-m3ex07jz/gipc-0.4.0/setup.py", line 22, in <module>
    
AttributeError: 'str' object has no attribute 'decode'
```

It works fine with python 2.

**Comment by heikoheiko** [comment]
pyethapp does not yet support py3

**Comment by zoidyzoidzoid** [comment]
@heikoheiko Is there interest in supporting Python 3, either with the same codebase or separately? I'd love to work on it.

**Comment by heikoheiko** [comment]
@zoidbergwill well that would be awesome. this would also involve the pyrlp, pyethereum, pydevp2p libraries. 
 pyrlp and pyethereum should have (some) py3 support already.

shall we have a chat on gitter?
https://gitter.im/ethereum/pyethapp
