### ISSUE TITLE
Handle data unavailability in getblockhashesfromnumber 

### ISSUE THREAD

**Issue by holiman** [ethereum/pyethapp#73]
Got this stack trace just now, on the 'real' network. 

```
INFO:p2p.peer   received hello client_version=Geth/v1.2.3/linux/go1.4.2 version=4 capabilities=(('eth', 62), ('eth', 61))
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.1b3-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 519, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/devp2p-0.5.8-py2.7.egg/devp2p/peer.py", line 212, in _run_decoded_packets
    self._handle_packet(self.mux.packet_queue.get())  # get_packet blocks
  File "/usr/local/lib/python2.7/dist-packages/devp2p-0.5.8-py2.7.egg/devp2p/peer.py", line 186, in _handle_packet
    protocol.receive_packet(packet)
  File "/usr/local/lib/python2.7/dist-packages/devp2p-0.5.8-py2.7.egg/devp2p/protocol.py", line 163, in receive_packet
    cmd(packet)
  File "/usr/local/lib/python2.7/dist-packages/devp2p-0.5.8-py2.7.egg/devp2p/protocol.py", line 135, in receive
    instance.receive(proto=self, data=klass.decode_payload(packet.payload))
  File "/usr/local/lib/python2.7/dist-packages/devp2p-0.5.8-py2.7.egg/devp2p/protocol.py", line 71, in receive
    cb(proto, **data)
  File "/usr/local/lib/python2.7/dist-packages/pyethapp-1.0.8-py2.7.egg/pyethapp/eth_service.py", line 495, in on_receive_getblockhashesfromnumber
    h = self.chain.index.get_block_by_number(i)
  File "/home/ubuntu/tools/pyethereum/ethereum/chain.py", line 67, in get_block_by_number
    return self.db.get(self._block_by_number_key(number))
  File "/usr/local/lib/python2.7/dist-packages/pyethapp-1.0.8-py2.7.egg/pyethapp/db_service.py", line 48, in get
    return self.db_service.get(key)
  File "/usr/local/lib/python2.7/dist-packages/pyethapp-1.0.8-py2.7.egg/pyethapp/leveldb_service.py", line 89, in get
    o = decompress(self.db.Get(key))
KeyError
<Greenlet at 0x7f56304e37d0: <bound method Peer._run_decoded_packets of <Peer('178.62.195.182', 30303) Geth/v1.2.2-2800c332>>> failed with KeyError
```

The app seems to keep running anyway, but looks like that shouldn't happen.

**Comment by panpilkarz** [comment]
Fixed: https://github.com/ethereum/pyethapp/commit/a4d442613b3cedb306ab8535fcde5b81d61d3a32#diff-d0d292569fbeef6755fb35e200079e5dR495
