### ISSUE TITLE
Console: AttributeError: 'InputHookManager' object has no attribute 'register'

### ISSUE THREAD

**Issue by bitcrab** [ethereum/pyethapp#88]
following issue occured in ubuntu 15.04, please help.
there is a closed issue with the same topic, but the answer there does not work for me : https://github.com/ethereum/pyethapp/issues/21

bitcrab@falcon:~/pyethapp$ pyethapp

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

Traceback (most recent call last):
  File "/usr/local/bin/pyethapp", line 9, in <module>
    load_entry_point('pyethapp==1.0.18', 'console_scripts', 'pyethapp')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 550, in load_entry_point

  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 2710, in load_entry_point

  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 2370, in load

  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 2376, in resolve

  File "/usr/local/lib/python2.7/dist-packages/pyethapp-1.0.18-py2.7.egg/pyethapp/app.py", line 21, in <module>
    from console_service import Console
  File "/usr/local/lib/python2.7/dist-packages/pyethapp-1.0.18-py2.7.egg/pyethapp/console_service.py", line 43, in <module>
    @inputhook_manager.register('gevent')
AttributeError: 'InputHookManager' object has no attribute 'register'
bitcrab@falcon:~/pyethapp$

**Comment by konradkonrad** [comment]
Hi @bitcrab,
I tried to reproduce your issue in a ubuntu 15.04 (container) and the only possible way for me was following these steps:

``` sh
user@host pyethapp$ python setup.py install
user@host pyethapp$ pip uninstall ipython
user@host pyethapp$ pip install ipython<3.0.0
```

so...I am pretty sure that, in order to solve your issue, you should

``` shell
user@host pyethapp$ pip install -U ipython
user@host pyethapp$ pyethapp
```

could you do that and see if the error persists?

**Comment by konradkonrad** [comment]
@bitcrab have you had time to test my proposed solution? https://github.com/ethereum/pyethapp/issues/88#issuecomment-178521465

**Comment by konradkonrad** [comment]
I assume this is solved, feel free to reopen @bitcrab
