### ISSUE TITLE
`blocktest` command is broken

### ISSUE THREAD

**Issue by konradkonrad** [ethereum/pyethapp#94]
```
git clone https://github.com/ethereum/rpc-tests
cd rpc-tests
git submodule --init

pyethapp -d /tmp/rpctests -l :info,eth.chainservice:debug,jsonrpc:debug -c jsonrpc.listen_port=8545 -c p2p.max_peers=0 -c p2p.min_peers=0 blocktest lib/tests/BlockchainTests/bcRPC_API_Test.json RPC_API_Test
INFO:app    using data in path=/tmp/rpctests
INFO:config loading config path=/tmp/rpctests
INFO:app    registering service service=db
WARNING:accounts    keystore directory does not exist directory=/tmp/rpctests/keystore
WARNING:accounts    no accounts found 
INFO:app    registering service service=accounts
INFO:p2p.discovery  NodeDiscovery init 
INFO:p2p.discovery  starting discovery proto this_enode=enode://643927c86ad07b9bc12e4d264a11f714ef3eb062cd7b89da322cda02ed1dd38a8ae551c34bfb482a74f8780a42e10b2db4d466dc4e64417b10b8cfb2d7213a9b@0.0.0.0:30303
INFO:app    registering service service=discovery
INFO:p2p.peermgr    PeerManager init 
INFO:app    registering service service=peermanager
INFO:eth.chainservice   initializing chain 
INFO:eth.chain  Initializing new chain 
INFO:eth.chain  new genesis difficulty=17179869184 genesis_hash=<Block(#0 d4e56740)>
INFO:eth.chainservice   chain at number=0
INFO:app    registering service service=chain
DEBUG:jsonrpc   initializing JSONRPCServer 
WARNING:jsonrpc could not import solidity 
INFO:app    registering service service=jsonrpc
DEBUG:jsonrpc   initializing IPCRPCServer 
WARNING:jsonrpc could not import solidity 
INFO:app    registering service service=ipc
INFO:app    registering service service=console
INFO:app    loading block file path=lib/tests/BlockchainTests/bcRPC_API_Test.json
Traceback (most recent call last):
  File "/home/konrad/.virtualenvs/pyethapp/bin/pyethapp", line 9, in <module>
    load_entry_point('pyethapp==1.0.18', 'console_scripts', 'pyethapp')()
  File "/home/konrad/.virtualenvs/pyethapp/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/konrad/.virtualenvs/pyethapp/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/konrad/.virtualenvs/pyethapp/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/konrad/.virtualenvs/pyethapp/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/konrad/.virtualenvs/pyethapp/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/konrad/.virtualenvs/pyethapp/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/konrad/Projects/pyethapp/pyethapp/app.py", line 293, in blocktest
    blocks = utils.load_block_tests(data.values()[0], app.services.chain.chain.db)
  File "/home/konrad/Projects/pyethapp/pyethapp/utils.py", line 99, in load_block_tests
    genesis(db, start_alloc=initial_alloc)  # builds the state trie
  File "/home/konrad/.virtualenvs/pyethapp/lib/python2.7/site-packages/ethereum-1.0.8-py2.7.egg/ethereum/blocks.py", line 1349, in genesis
    assert isinstance(env, Env)
AssertionError

```

**Comment by konradkonrad** [comment]
See also #29
